[project]
name = "finance-tracker-personal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "questionary>=2.1.1",
    "rich>=14.2.0",
]
